### ISSUE TITLE
Search Bar Styled Wrong - Google Drive Dark

### ISSUE THREAD

**Issue by Obscure2020** [Gravitonic/userstyles#1]
I'm experiencing issues with Google Drive Dark.
Almost everything looks fine, and I appreciate the ability to set a custom accent color.
Unfortunately, there are styling problems with the Search bar.

Right now, it looks like this:
![image](https://user-images.githubusercontent.com/69320464/151885227-dfe04967-6c92-469a-bbd4-27f851431667.png)

Interestingly, though, if I _click_ on the search bar, it seems to fix itself:
![image](https://user-images.githubusercontent.com/69320464/151885311-7d5746c3-4f3c-4e39-a8c3-38c3be3806eb.png)

In addition, if I type something in the search bar, the text is dark instead of light.
I get the feeling that's not right either.
![image](https://user-images.githubusercontent.com/69320464/151885464-d8422361-6c61-4ddd-9d14-c241d5b18f7c.png)

**Comment by Gravitonic** [comment]
Google changed their CSS classes again and I didn't get around to fixing them. Should now be resolved if you update the style.

Fixed in 6af68f67e37e9eb051eef18be8cfa5f1dc3d9963

**Comment by Obscure2020** [comment]
![image](https://user-images.githubusercontent.com/69320464/151921757-cc6e17c6-bb9d-4446-8281-2aa90424cca8.png)
