### ISSUE TITLE
Broken styling on Google Drive

### ISSUE THREAD

**Issue by remaindeer** [Gravitonic/userstyles#2]
Hi, the recent changes in Google Drive unfortunately results in a pretty broken styling situation. Could you please take a look at it? I'm attaching an example screenshot
![cde146d1-5010-49f5-9aa6-677c71bf3da1](https://user-images.githubusercontent.com/402154/170397233-b42eaa81-8d4a-4497-82c5-fae85a78f667.png)
.

**Comment by Gravitonic** [comment]
Thanks for the bug report! It should be mostly cleaned up now (if you fetch the latest update), but I'll leave this open in case I missed anything, seeing as it looks like a pretty big update.

**Comment by remaindeer** [comment]
Thanks so much for the quick response, looks great!
