### ISSUE TITLE
Styling issue with Google Drive

### ISSUE THREAD

**Issue by remaindeer** [Gravitonic/userstyles#3]
![drive](https://user-images.githubusercontent.com/402154/178013053-1524ff51-e830-449b-b2f1-e5e226342244.png)

Hi, the most recent update to Google Drive unfortunately broke the styling. Could you take a look at it?

**Comment by Furshia** [comment]
Same issue hope it gets fixed soon, it's blinding me

**Comment by berserker465** [comment]
Same here, what a pain for my eyes x.x

**Comment by Gravitonic** [comment]
Fixed in 1073df4. Feel free to open another issue if the problem persists.
