### ISSUE TITLE
Picture in My Drive on the right is white

### ISSUE THREAD

**Issue by Furshia** [Gravitonic/userstyles#4]
![image](https://user-images.githubusercontent.com/99036848/178453777-946ce2d6-cb65-48c2-bbbf-745567c8177f.png)

Is there a way to theme this as well? I know it's minimal but would appreciate if its also themed :) Thank you

**Comment by Gravitonic** [comment]
Had to pull out Photoshop, so it's a little sloppy around the edges if you look closely. If anyone wants to complain, they're welcome to open a new issue 😛
