### ISSUE TITLE
Styling issue with Google Workspace

### ISSUE THREAD

**Issue by Kaillis** [Gravitonic/userstyles#6]
Share menu and starred regions are white, hope you can fix it.
You made wonderful styles, thank you. :smiley:

![2022-8-6 23-14-44](https://user-images.githubusercontent.com/20882298/183255532-7605f4a2-c187-4841-bfd8-a1ac7795e6ed.png)

![2022-8-6 23-16-52](https://user-images.githubusercontent.com/20882298/183255534-ef644915-2ee6-4d0a-a226-738e247d3884.png)

**Comment by Gravitonic** [comment]
File paths for starred items, search results, etc. should be fixed with v0.2.13.

Share menu is still a work-in-progress at this time.

**Comment by Gravitonic** [comment]
It seems like the share menu is now styled due to some changes in other areas and on Google's end. I'll close this for now but feel free to re-open with any new styling errors.
