### ISSUE TITLE
Broken styling on Drive homepage

### ISSUE THREAD

**Issue by remaindeer** [Gravitonic/userstyles#7]
Hi, it seems the recent updates have broken the styling on the home page. Could you please take a look at it? Thank you in advance.

![image](https://user-images.githubusercontent.com/402154/227341853-ee614d84-124b-4303-85e5-e8272d7b8407.png)

**Comment by Gravitonic** [comment]
It seems like it took a bit for the new design to get rolled out to me, but I'm seeing this now as well and looking into it.

**Comment by Gravitonic** [comment]
This should be fixed with 574b4ae, so I'll be closing this — please feel free to open another issue if you're still seeing those issues!
