### ISSUE TITLE
[GDD] Fix text color in search bar

### ISSUE THREAD

**Issue by Korb** [Gravitonic/userstyles#8]
![2023-06-25_15-16-28](https://github.com/Gravitonic/userstyles/assets/3509797/8dc02808-1423-4118-905c-d6d6f5161779)

Mozilla Firefox 115.0b9 (64-bit)
Stylus 1.5.33 (June 11, 2023)
Microsoft Windows 10.0.19045.3086

**Comment by Gravitonic** [comment]
This should be fixed with 66dfdd6 (v0.2.16). Please feel free to open another issue if you're still seeing those issues!
